### ISSUE TITLE
Feature: Helm 3 support

### ISSUE THREAD

**Issue by javiertoledos** [Stono/helm-test#11]
Hello, I want to add support to helm 3. I started using this library and I find it helpful but considering the current helm version I think this package needs an update.

Currently, the helm template command uses the --name flag, which is removed from helm 3. I'm submitting a PR with the feature request.

**Comment by Stono** [comment]
This is resolved now, 0.5.0 introduces dynamic helm version detection

https://github.com/Stono/helm-test/commit/c5c4c1b1ca603a6bc077d8d0c2df81982b5a5166
